// This file is auto-generated by `flutterfire configure`.
// Run the following after setting up Firebase:
//   1. Install Firebase CLI: npm install -g firebase-tools
//   2. Login: firebase login
//   3. Install flutterfire CLI: dart pub global activate flutterfire_cli
//   4. Generate: flutterfire configure
//
// Until then, this placeholder prevents compilation errors.
// The app will not connect to Firestore without this file properly configured.

// ignore_for_file: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.appformom.appForMom',
  );
}
