// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Only iOS is supported.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjcPmJINs5UXNJpKgDsaJwnF9iy2jv13s',
    appId: '1:213660407692:ios:ee828541975bf6fb6f28a9',
    messagingSenderId: '213660407692',
    projectId: 'app-for-mom-d54a2',
    storageBucket: 'app-for-mom-d54a2.firebasestorage.app',
    iosBundleId: 'com.appformom.appForMom',
  );
}
